@namePrefix = <your_prefix>
@apimName = <your_apim_name>
@workflowName = <logic_app_workflow>
@workflowSasKey = <workflow_local_logic_app_signature>

## Test Logic App API locally
GET http://localhost:7071/api/{{workflowName}}/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig={{workflowSasKey}}

### Test Front door health check for API Management backend
GET https://{{namePrefix}}-fd.azurefd.net/status-0123456789abcdef

### Test APIM Public Endpoint (should timeout after setting Network Sercurity Group rule on allowing only Inbound traffic from Front Door to APIM)
GET https://{{apimName}}.azure-api.net/echo/resource?param1=sample

### Test APIM Echo API via Front Door (remove the subscription key security for testing)
GET https://{{namePrefix}}-fd.azurefd.net/echo/resource?param1=sample

### Test APIM endpoint with Logic App backend
GET https://{{namePrefix}}-fd.azurefd.net/ase/get